### ISSUE TITLE
[Error] Cannot search CPUs and GPUs with name in buildupgrader.html(Build Upgrade Calculator).

### ISSUE THREAD

**Issue by reatomy** [pcbstools/issuetracker#1]
**Describe the error**
I cannot search current CPU or GPU with typing parts of its name.
(Onchange function doesn't work)
If I run the function in console, it shows some errors in calc.js.

**To Reproduce**
1. Go to 'buildupgrader.html'
2. Type some text in 'Current CPU'

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8073935/52331572-e088a780-2a3b-11e9-9e17-6190485a2bcd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 72.0.3626.81

**Mobile (please complete the following information):**
 - Device: [e.g. iPhone6, Samsung Galaxy S10]
 - OS: [e.g. iOS8.1, Android 9.0]
 - Browser [e.g. stock browser, safari, Samsung Browser]

**Additional context**

**Comment by AhRoon** [comment]
This issue already fixed. Please refer to the Steam Group for updates. Closed.

**Comment by AhRoon** [comment]
Oops, Sorry. I forgot to fix this issues. Please wait.

**Comment by AhRoon** [comment]
Thank you for reporting! Now it's fixed. Please remember to reload the page to take effect.
Have a nice day!

This issue will be closed.

P.S. By the way, congratulation for making first issues on our issue tracker!

**Comment by reatomy** [comment]
Thanks for your fast supports.
But I think it still has some errors.
Console says another error message when I use Build Upgrade Calculator(I think it's about CPU part).
And In input field for CPU name, the dropdown? options are about GPUs.
Should I open another issue?

**Comment by reatomy** [comment]
And it doesn't work :(

**Comment by AhRoon** [comment]
> Thanks for your fast supports.
> But I think it still has some errors.
> Console says another error message when I use Build Upgrade Calculator(I think it's about CPU part).
> And In input field for CPU name, the dropdown? options are about GPUs.
> Should I open another issue?

> And it doesn't work :(

Fixed. Please make another issues next time.
