### ISSUE TITLE
[Error] Including RAM in BuildMaker causes no builds.

### ISSUE THREAD

**Issue by wolfcry420** [pcbstools/issuetracker#3]
**Describe the error**
BuildMaker will not generate any builds with "Include RAM" checked.

**To Reproduce**
1. Select "Include RAM"
2. Click on 'Generate'
3. See error "No Builds can be found"

**Expected behavior**
A list of builds that include all items (including RAM modules).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version: 68.0.1 64-bit

**Additional context**
While Buildmaker can be used without including RAM (just have select which modules in game), the Upgrade calculator is completely unusable as it will always bail with a "can't find a build" error.

**Comment by wolfcry420** [comment]
Correct.  The Upgrade calculator seems to be working at the moment.  It was not earlier.

**Comment by wolfcry420** [comment]
I found the problem
in your generateBuild() method, you have it checking data.ram[ramms].frequency  ..  That element doesn't exist.  Instead all 5 instances of of data.ram[ramms].frequency should be changed to data.ram[ramms].baseFreq

**Comment by AhRoon** [comment]
Issue already fixed in the latest update. Please do not make duplicated issues and do not abuse close issue otherwise I can't help you about this.
