### ISSUE TITLE
Include v1.5 parts

### ISSUE THREAD

**Issue by fnqista** [pcbstools/issuetracker#4]
**Feature Description**
Update to include v1.5 parts (Ryzen 3 processors, ASRock graphic cards, etc)

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by AhRoon** [comment]
Update will be posted after biubiu posts an update, please wait warmly until the update is able to be published.

**Comment by AhRoon** [comment]
Update v1.5 Released.

Issue closed.

P.S. Next time please check announcement on our Steam Group.

**Comment by fnqista** [comment]
Thanks for the quick turn-around
