### ISSUE TITLE
3900X Overclocked Score

### ISSUE THREAD

**Issue by whitebow** [pcbstools/issuetracker#5]
In the Part ranking tool, there is an issue with the 3900X : 
I got 16 311 with it when Overclocked, and it's 8312 in the part ranking.

**Screenshots**
https://i.imgur.com/d1nV56Q.jpg    (it's my cheated savegame)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: ?

**Comment by AhRoon** [comment]
Will be fixed on v1.5.1 Update.

**Comment by AhRoon** [comment]
Updated. Please refresh the page in order to take effect.
