### ISSUE TITLE
Calculator doesn't work anymore

### ISSUE THREAD

**Issue by DarkFighterLuke** [pcbstools/issuetracker#6]
**Describe the error**
A clear and concise description of what the error is.

**To Reproduce**
1. Go to 'Build Upgrader'

**Expected behavior**
I expect a list of results, but there is no list.
If I set 'Target Score' to at least 5375, it works.

**Screenshots**
![image](https://user-images.githubusercontent.com/31162436/70653453-d4b9d300-1c54-11ea-8825-461c7b7e833e.png)
![image](https://user-images.githubusercontent.com/31162436/70653842-86590400-1c55-11ea-8e2c-9cd657b1b2a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera, Firefox
 - Version 65.0.3467.62

**Comment by AhRoon** [comment]
It's really strange, biubiu might need to fix this. I will talk about this bug to biubiu. This may take several days to be fixed.

**Comment by AhRoon** [comment]
Status Update - I found that calculator does not even work your new.html. It is probably the calculator issue.

**Comment by DarkFighterLuke** [comment]
Can it be solved?

**Comment by JacobWKlein** [comment]
For "Target Score Offset", if it is set to 200, there are 0 upgrades that can result in a score of 5348-5548.

If you set "Target Score Offset" to something like 9999, and set "Number of Result" to something like 9999, then you will see the full list of results... none of which have a score less than 5574, which is still ABOVE 5548.

So, I don't think it's broken.

**Comment by AhRoon** [comment]
Thank you @JacobWKlein.
Issue will be closed since this is not a bug.
Next time try other ways to display properly before reporting issues.
