### ISSUE TITLE
[Error] SLI/Crossfire can be applied on Unsupported Motherboard

### ISSUE THREAD

**Issue by Isnarintas** [pcbstools/issuetracker#7]
In the build maker, if you choose to build any build, sometimes with SLI/Crossfire cards the motherboard GIGABYTE GA-AB350M-Gaming 3 is suggested, which doesn't support SLI/Crossfire
(The non-M version does support Multi-GPU, so I think that's the one it should be suggesting)

**Comment by AhRoon** [comment]
Asking to biubiu about this issue, hold on!

**Comment by DSlite** [comment]
I think it's not only on GIGABYTE GA-AB350M-Gaming 3, but other motherboard that doesn't support SLI/Crossfire has the same problem. If you try using the build upgrader with motherboard that doesn't support SLI/Crossfire, it still suggest to use multi-GPU

**Comment by AhRoon** [comment]
> I think it's not only on GIGABYTE GA-AB350M-Gaming 3, but other motherboard that doesn't support SLI/Crossfire has the same problem. If you try using the build upgrader with motherboard that doesn't support SLI/Crossfire, it still suggest to use multi-GPU

> In the build maker, if you choose to build any build, sometimes with SLI/Crossfire cards the motherboard GIGABYTE GA-AB350M-Gaming 3 is suggested, which doesn't support SLI/Crossfire
> (The non-M version does support Multi-GPU, so I think that's the one it should be suggesting)

biubiu doesn't respond, so I cannot fix this issue atm. Sorry!

**Comment by AhRoon** [comment]
Okay biubiu posted a hotfix, will be patched tomorrow because it's late for me.

**Comment by AhRoon** [comment]
Hotfix posted, see the What's new? in Navigation Bar for changes.
Thank you for reporting issues!

Issue Closed #7.

**Comment by AhRoon** [comment]
Sorry forgot to add Resolved tag :(
