### ISSUE TITLE
[Error] Build Upgrader does not account for Max RAM Speed on Motherboards

### ISSUE THREAD

**Issue by iRoxor** [pcbstools/issuetracker#8]
< Information START >

As the title suggests, motherboards have a maximum RAM clock speed which severely impacts 3DMark benchmark test scores, and the Build Upgrader does not notify if the currently selected motherboard can clock to the max speed of the currently selected RAM. This can lead to unknowledgable players buying RAM sticks to meet a target score only to realize that they need to replace the entire motherboard, cutting into their allotted budget.

On that note, there should always be an alert to remind the player to overclock the system in the BIOS no matter what section of the PCBS Calculator you are in.

***DO NOT REMOVE ANY FORMS HERE, PLEASE FOLLOW THE FORM TO GET ASSISTANCE EASILY***

**Before you post a issue, did you tried...**
* Changing the Score offset value? **N/A**
* Opening a Console(F12) and see there is an error? **N/A**
* Contacting original author(e.g. biubiu, beyondpower)? **N/A**
(You don't need to answer here, it's just information about reporting issues.)

< END of Information >

**Please provide screenshots here.**
https://i.imgur.com/VQpOAcU.png

https://i.imgur.com/uljQIje.png

**Please describe the error with more information.**
As shown in the screenshots, it would be ideal if the PCBS Calculator would notice the discrepancy in the mismatching Max RAM Speeds much like "PCPartPicker" would give you incompatibility and "additional info" alerts and provide motherboard replacement options in the results.

**Your Device Information**
 - OS: [e.g. Windows, iOS, Linux, Android] **N/A**
 - Browser [e.g. Chrome, Safari, Opera, etc] **N/A**
 - Version [e.g. 80] **N/A**
 - Device Info(Only enter if you're using Android/iOS and other Mobile Devices) [e.g. Samsung Galaxy S20 Ultra] **N/A**

**Additional Information**

**Comment by AhRoon** [comment]
I've contacted biubiu and will be fixed on next v1.7 update!

**Comment by xLeeJYx** [comment]
should be fixed in the newest update

**Comment by AhRoon** [comment]
Thanks for the report! Issues has been fixed on v1.7_01 update. Stay safe and have a nice day :)
Closed #8.
